export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const GET_CURR_PROFILE = 'GET_CURR_PROFILE';

export const GET_POST = 'GET_POST';
export const GET_POSTS = 'GET_POSTS';
export const GET_USERS_POSTS = 'GET_USERS_POSTS';
export const CLEAR_POST = 'CLEAR_POST';
export const CLEAR_POSTS = 'CLEAR_POSTS';
export const POST_ERROR = 'POST_ERROR';
export const POST_POST = 'POST_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const LIKE_POST = 'LIKE_POST';
export const UNLIKE_POST = 'UNLIKE_POST';
export const GET_COMMENTS = 'GET_COMMENTS';
export const COMMENT_POST = 'COMMENT_POST';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const GET_SAVED_POST = 'GET_SAVED_POST';
export const UPDATE_SAVED_POST = 'UPDATE_SAVED_POST';
export const SAVED_POST_ERROR = 'SAVED_POST_ERROR';

export const GET_USER_CONVERSATIONS = 'GET_USER_CONVERSATIONS';
export const CREATE_CONVERSATION = 'CREATE_CONVERSATION';
export const GET_CONVERSATION = 'GET_CONVERSATION';
export const CONVERSATION_ERROR = 'CONVERSATION_ERROR';

export const GET_MESSAGES = 'GET_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';
export const ADD_MESSAGE = 'ADD_MESSAGE';